language: java

jdk:
  - oraclejdk8

after_success:
- mvn clean site-deploy

env:
  global:
    secure: IG54EcGrWg+l8azSBH+7jgyRKpBCD1kUSYflPzhLBo8YpbUi7x+EhwKdg+TCYVsUzbG1YWGUXmtrpM5jJa7NsOBLSpTKmSme7DMzlTqeJzLaepuYG5ksUp1KGzMg9WtG97KTn3wjGqu7oJYr1mozAPWK+PrgW6LsffbbDjRUcEXqZyOP1v7B/CISI+SKbXJiBUpAe243DHT5h5eR5HYGGei7//Znrm9tdKQOKT0p7xp1z+Az+im7v7hfirRNIiwB+qQOLpAfHPvk1dDKtM4jpQT/xkDRKq1kTAtmcc+gqnIzfh83pmuzacNlWoaSs8OWSUX2+sxsWK+ojXxcla2i9Ob5ksdGwJRZ+GvJGgYw9whlNGLGMVYNMikfysqFIRZUN7n1h8N4v8497HniUtwq1Mk1eJtckhHV0zghSFl3WRTjuIZNnA+aflwQvceiuGBZdpX/Fn+Cgl9mTjozuQQlJTRnZjSL8bXmGVARcjjnHuF7g0+4XUZyryZ/PUB9vLRWxdwUo8eKaDhLbryZT6Zf6f0FMUJBfngJfWdN4TW7ryF71Ttq3MSKwTIdO57mlhaduVKvBSKhTLW5AQzUjHZWt3nQVAaizuB9aHE7B7TZtwCphDtV0QgDSE5LeCX9nOfE0JrU/KqoQNgbEiv9FZcb/z6cEGpK4Von7wPob8GzaBU=
